create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  reviewer_name text not null,
  rating integer not null check (rating between 1 and 5),
  comment text not null,
  created_at timestamptz not null default now()
);

alter table public.reviews enable row level security;

drop policy if exists "Anyone can read reviews" on public.reviews;
drop policy if exists "Anyone can create reviews" on public.reviews;
drop policy if exists "Anyone can update reviews" on public.reviews;
drop policy if exists "Anyone can delete reviews" on public.reviews;

create policy "Anyone can read reviews"
  on public.reviews for select
  to anon
  using (true);

create policy "Anyone can create reviews"
  on public.reviews for insert
  to anon
  with check (true);

create policy "Anyone can update reviews"
  on public.reviews for update
  to anon
  using (true)
  with check (true);

create policy "Anyone can delete reviews"
  on public.reviews for delete
  to anon
  using (true);
