create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null,
  price numeric(10, 2) not null check (price >= 0),
  tone text not null,
  description text not null,
  features text[] not null default '{}'
);

create table public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create table public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  reviewer_name text not null,
  rating integer not null check (rating between 1 and 5),
  comment text not null,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.contact_messages enable row level security;
alter table public.reviews enable row level security;

create policy "Anyone can read products"
  on public.products for select
  to anon
  using (true);

create policy "Anyone can submit contact messages"
  on public.contact_messages for insert
  to anon
  with check (true);

create policy "Anyone can read reviews"
  on public.reviews for select
  to anon
  using (true);

create policy "Anyone can create reviews"
  on public.reviews for insert
  to anon
  with check (true);

create policy "Anyone can update reviews"
  on public.reviews for update
  to anon
  using (true)
  with check (true);

create policy "Anyone can delete reviews"
  on public.reviews for delete
  to anon
  using (true);

insert into public.products (name, type, price, tone, description, features)
values
  ('Signal Notes', 'Template', 12, 'coral', 'A focused workspace for turning loose ideas into clear next steps.', array['Weekly planning board', 'Decision journal', 'Printable review pages']),
  ('Field Guide', 'Guide', 18, 'teal', 'A practical digital guide for building a calmer creative practice.', array['Six learning chapters', 'Reflection prompts', 'Progress checklist']),
  ('Studio Kit', 'Bundle', 29, 'gold', 'A compact set of tools for planning, presenting, and shipping work.', array['Three editable templates', 'Project launch checklist', 'Client handoff notes']),
  ('Quiet Launch', 'Mini-course', 24, 'plum', 'A short, practical course for sharing a project with confidence.', array['Four short lessons', 'Launch worksheet', 'Email announcement kit']);
